# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: EvarinthoSec.mtop
PackageVersion: "0.1.0-alpha.1"
Platform:
- Windows.Desktop
Installers:
- Architecture: x64
  InstallerType: zip
  InstallerUrl: https://github.com/EvarinthoSec/mtop/releases/download/v0.1.0-alpha.1/mtop-windows-x86_64-0.1.0-alpha.1.zip
  InstallerSha256: 318d37d7df16b05fc72a07aebff88e8435fd8d6e6cda08b56c6a7dac356aa3bc
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: mtop.exe
    PortableCommandAlias: mtop
ManifestType: installer
ManifestVersion: 1.12.0
