# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: EvarinthoSec.mtop
PackageVersion: "1.0.0"
Platform:
- Windows.Desktop
Installers:
- Architecture: x64
  InstallerType: zip
  InstallerUrl: https://github.com/EvarinthoSec/mtop/releases/download/v1.0.0/mtop-windows-x86_64-1.0.0.zip
  InstallerSha256: 6c7f4c9fec9a121ab109d0e02e0ded39bd65efcc09a5a9ff25a1f2285b42c73b
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: mtop.exe
    PortableCommandAlias: mtop
ManifestType: installer
ManifestVersion: 1.12.0
